image: alpine:latest

stages:
  - build
  #- test
  - deploy

before_script:
  - apk add dotnet6-sdk

build-release-windows:
  stage: build
  #rules:
    #- if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - build/release/
  script:
    # The output path is relative to the position of the csproj-file
    - dotnet publish "./AvatarController/AvatarController.sln" -c "Release" -r win10-x64 -o "./build/release/" --no-self-contained

#test:
# stage: test
  #script:
    # The output path is relative to the position of the csproj-file
    #- msbuild /p:Configuration="Debug" /p:Platform="Any CPU"
    #  /p:OutputPath="./../../build/debug/" "MyProject.sln"
    #- mono packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe build/debug/MyProject.Test.dll

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
